output_path: "/scratch/indikar_root/indikar1/shared_data/directRNA/"
ref_path: "/nfs/turbo/umms-indikar/shared/projects/directRNA/reference/Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz" 
annotations_path: "/nfs/turbo/umms-indikar/shared/projects/directRNA/reference/Homo_sapiens.GRCh38.107.gtf"
fastq_path: "/nfs/turbo/umms-indikar/shared/projects/directRNA/reads/"
R_path: "~/miniconda3/bin/Rscript"
minimap2_args: "-ax splice -uf -k14"
minQual: 0
threads: 36
